# filepath: my-helm-chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-modelversions
data:
  modelversions.yaml: |
{{ tpl (.Files.Get "assets/modelversions.yaml") . | indent 4 }}
  